#! /usr/bin/env bash

# Gradle project
if [ -f gradlew ]; then
  echo "This is a Gradle project. Build before push."
  ./gradlew build
  exit $?
fi

# OMake project
  if [ -f OMakefile ]; then
   echo "This is a OMake project. Make before push."
   omake
   exit $?
fi

exit 0
